language: php
os: linux
dist: xenial

notifications:
  email: false

php:
  - 7.0

branches:
  only:
    - master
    - trunk
    - compat/ppxo

script: |
  CHANGED_FILES=`git diff --name-only --diff-filter=ACMR $TRAVIS_COMMIT_RANGE | grep \\\\.php | awk '{print}' ORS=' '`

  if [ "$CHANGED_FILES" != "" ]; then
    composer global require woocommerce/woocommerce-sniffs --update-with-all-dependencies
    $HOME/.config/composer/vendor/bin/phpcs -p $CHANGED_FILES
  fi
