name: e2e tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.1']
        wc-versions: ['5.9.5', '7.7.2']

    name: PHP ${{ matrix.php-versions }} WC ${{ matrix.wc-versions }}
    steps:
    - uses: ddev/github-action-setup-ddev@v1
      with:
        autostart: false

    - uses: actions/checkout@v1

    - name: Configure DDEV PHP
      run: ddev config --php-version ${{ matrix.php-versions }}
    - name: Configure DDEV WC
      run: ddev config --web-environment-add="WC_VERSION=${{ matrix.wc-versions }}"

    - name: Start DDEV
      run: ddev start

    - name: Orchestrate DDEV
      run: ddev orchestrate -f

    - name: Create config
      run: cp -n .env.e2e.example .env.e2e

    - name: Setup tests
      run: ddev php tests/e2e/PHPUnit/setup.php

    - name: Run PHPUnit
      run: ddev exec phpunit -c tests/e2e/phpunit.xml.dist
