name: Build package

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Package version'
        required: false
        type: string

jobs:
  create_archive:
    uses: inpsyde/reusable-workflows/.github/workflows/build-plugin-archive.yml@main
    with:
      PHP_VERSION: 7.2
      PLUGIN_MAIN_FILE: ./woocommerce-paypal-payments.php
      PLUGIN_VERSION: ${{ inputs.packageVersion }}
